import { nanoid } from 'https://cdn.jsdelivr.net/npm/nanoid/nanoid.js';

import {
  linenblendshirt,
  linenblendshirt2,
  fivepackstrappytops,
  fivepackstrappytops2,
  boxyjumper,
  boxyjumper2,
  chunkyloafers,
  chunkyloafers2,
  cottontrenchcoat,
  cottontrenchcoat2,
  doublebreastedblazer,
  doublebreastedblazer2,
  doublebreastedtrenchcoat,
  doublebreastedtrenchcoat2,
  fineknitcashmerecardigan,
  fineknitcashmerecardigan2,
  flounceddress,
  flounceddress2,
  grandpacollardress,
  grandpacollardress2,
  hoodedpuffergilet,
  hoodedpuffergilet2,
  juteblendshopper,
  juteblendshopper2,
  lacetrimmedshirtdress,
  lacetrimmedshirtdress2,
  leatherbelt,
  leatherbelt2,
  longflaredsatinskirt,
  longflaredsatinskirt2,
  miniskirt,
  miniskirt2,
  oversizedTshirt,
  oversizedTshirt2,
  rhinestonebuttonblazer,
  rhinestonebuttonblazer2,
  ribbedhenleytop,
  ribbedhenleytop2,
  ribknittop,
  ribknittop2,
  shacket,
  shacket2,
  singlebreastedjacket,
  singlebreastedjacket2,
  slingbacks2,
  slingbacks,
  straightjoggers,
  straightjoggers2,
  tailoredminiskirt,
  tailoredminiskirt2,
  texturedweavejacket,
  texturedweavejacket2,
  tiebeltcoat,
  tiebeltcoat2,
  trainers,
  trainers2,
  wrapdress,
  wrapdress2,
} from './imagesImport';

const productArray = [
  {
    id: nanoid(15),
    name: 'Shacket',
    cost: '€69.99',
    src: shacket,
    src2: shacket2,
    category: ['Trending now', 'Coats'],
  },
  {
    id: nanoid(15),
    name: 'Single-breasted Jacket',
    cost: '€49.99',
    src: singlebreastedjacket,
    src2: singlebreastedjacket2,
    category: ['Blazers'],
  },
  {
    id: nanoid(15),
    name: 'Rib-knit Top',
    cost: '€14.99',
    src: ribknittop,
    src2: ribknittop2,
    category: ['Trending now', 'T-Shirts'],
  },
  {
    id: nanoid(15),
    name: 'Double-breasted Blazer',
    cost: '€34.99',
    src: doublebreastedblazer,
    src2: doublebreastedblazer2,
    category: ['Trending now', 'Blazers'],
  },
  {
    id: nanoid(15),
    name: 'Linen-blend shirt',
    cost: '€49.99',
    src: linenblendshirt,
    src2: linenblendshirt2,
    category: ['Trending now'],
  },
  {
    id: nanoid(15),
    name: 'Flounced dress',
    cost: '€29.99',
    src: flounceddress,
    src2: flounceddress2,
    category: ['Trending now', 'Dresses'],
  },

  {
    id: nanoid(15),
    name: 'Straight joggers',
    cost: '€24.99',
    src: straightjoggers,
    src2: straightjoggers2,
    category: ['New Arrivals'],
  },
  {
    id: nanoid(15),
    name: 'Rhinestone-button Blazer',
    cost: '€49.99',
    src: rhinestonebuttonblazer,
    src2: rhinestonebuttonblazer2,
    category: ['Blazers'],
  },
  {
    id: nanoid(15),
    name: 'Tie-belt coat',
    cost: '€49.99',
    src: tiebeltcoat,
    src2: tiebeltcoat2,
    category: ['New Arrivals', 'Coats'],
  },
  {
    id: nanoid(15),
    name: 'Lace-trimmed shirt dress',
    cost: '€39.99',
    src: lacetrimmedshirtdress,
    src2: lacetrimmedshirtdress2,
    category: ['New Arrivals', 'Dresses'],
  },
  {
    id: nanoid(15),
    name: 'Double-breasted trenchcoat',
    cost: '€69.99',
    src: doublebreastedtrenchcoat,
    src2: doublebreastedtrenchcoat2,
    category: ['Coats'],
  },
  {
    id: nanoid(15),
    name: 'Oversized T-shirt',
    cost: '€21.99',
    src: oversizedTshirt,
    src2: oversizedTshirt2,
    category: ['T-Shirts'],
  },
  {
    id: nanoid(15),
    name: '5-pack strappy tops',
    cost: '€15.99',
    src: fivepackstrappytops,
    src2: fivepackstrappytops2,
    category: ['New Arrivals', 'T-Shirts'],
  },
  {
    id: nanoid(15),
    name: 'Boxy jumper',
    cost: '€99.99',
    src: boxyjumper,
    src2: boxyjumper2,
    category: ['New Arrivals'],
  },
  {
    id: nanoid(15),
    name: 'Wrap dress',
    cost: '€109',
    src: wrapdress,
    src2: wrapdress2,
    category: ['Dresses'],
  },
  {
    id: nanoid(15),
    name: 'Hooded puffer gilet',
    cost: '€119.99',
    src: hoodedpuffergilet,
    src2: hoodedpuffergilet2,
    category: ['BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Fine-knit cashmere cardigan',
    cost: '€129.99',
    src: fineknitcashmerecardigan,
    src2: fineknitcashmerecardigan2,
    category: ['New Arrivals', 'BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Chunky loafers',
    cost: '€34.99',
    src: chunkyloafers,
    src2: chunkyloafers2,
    category: ['Shoes', 'BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Textured-weave jacket',
    cost: '€69.99',
    src: texturedweavejacket,
    src2: texturedweavejacket2,
    category: ['New Arrivals', 'Blazers'],
  },
  {
    id: nanoid(15),
    name: 'Slingbacks',
    cost: '€239.99',
    src: slingbacks,
    src2: slingbacks2,
    category: ['New Arrivals', 'Shoes'],
  },
  {
    id: nanoid(15),
    name: 'Mini skirt',
    cost: '€19.99',
    src: miniskirt,
    src2: miniskirt2,
    category: ['Skirts', 'BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Trainers',
    cost: '€29.99',
    src: trainers,
    src2: trainers2,
    category: ['Shoes', 'BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Jute-blend shopper',
    cost: '€39.99',
    src: juteblendshopper,
    src2: juteblendshopper2,
    category: ['Accessories', 'Trending now'],
  },
  {
    id: nanoid(15),
    name: 'Leather belt',
    cost: '€19.99',
    src: leatherbelt,
    src2: leatherbelt2,
    category: ['Accessories', 'BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Long Flared Satin Skirt',
    cost: '€29.99',
    src: longflaredsatinskirt,
    src2: longflaredsatinskirt2,
    category: ['Skirts'],
  },
  {
    id: nanoid(15),
    name: 'Cotton trenchcoat',
    cost: '€59.99',
    src: cottontrenchcoat,
    src2: cottontrenchcoat2,
    category: ['Coats', 'BestSellers'],
  },
  {
    id: nanoid(15),
    name: 'Tailored Mini Skirt',
    cost: '€15.99',
    src: tailoredminiskirt,
    src2: tailoredminiskirt2,
    category: ['Skirts', 'Trending now'],
  },
  {
    id: nanoid(15),
    name: 'Ribbed Henley Top',
    cost: '€19.99',
    src: ribbedhenleytop,
    src2: ribbedhenleytop2,
    category: ['BestSellers', 'T-Shirts'],
  },
  {
    id: nanoid(15),
    name: 'Grand pacollar dress',
    cost: '€35.99',
    src: grandpacollardress,
    src2: grandpacollardress2,
    category: ['Dresses'],
  },
];

export default productArray;
